backend:
    name: github
    repo: coloradocolby/colby.sh
media_folder: src/assets
public_folder: assets
collections:
    - name: blog
      label: Blog
      folder: blog
      create: true
      fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
    - name: projects
      label: Projects
      folder: projects
      create: true
      fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
          - label: "CardInfo"
            name: "card_info"
            widget: "object"
            fields:
                - {
                      label: "ProjectName",
                      name: "project_name",
                      widget: "string",
                  }
                - {
                      label: "Description",
                      name: "description",
                      widget: "string",
                  }
                - {
                      label: "PreviewImage",
                      name: "preview_image",
                      widget: "image",
                  }
                - {
                      label: "Technologies",
                      name: "technologies",
                      widget: "list",
                  }
