backend:
    name: github
    repo: coloradocolby/colby.sh

media_folder: static/img
public_folder: /img

collections:
    - name: blog
      label: Blog
      folder: src/blog
      create: true
      fields:
          - {
                label: Template Key,
                name: templateKey,
                widget: hidden,
                default: blog-post,
            }
          - { label: Path, name: path, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Published Date, name: date, widget: datetime }
          - { label: Description, name: description, widget: string }
          - { label: Featured Image, name: featuredImage, widget: image }
          - { label: Body, name: body, widget: markdown }
          - { label: Tags, name: tags, widget: list }

    - name: projects
      label: Projects
      folder: src/projects
      create: true
      fields:
          - {
                label: Template Key,
                name: templateKey,
                widget: hidden,
                default: blog-post,
            }
          - { label: Path, name: path, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Published Date, name: date, widget: datetime }
          - { label: Description, name: description, widget: string }
          - { label: Featured Image, name: featuredImage, widget: image }
          - { label: Body, name: body, widget: markdown }
          - { label: Tags, name: tags, widget: list }
